if: tag IS blank

env:
  - ghc=8.4.2
  - ghc=8.6.5
  - ghc=8.8.1 benchmarks=1 tests=1
  - ghc=8.10.1

matrix:
  allow_failures:
    - env: ghc=8.10.1

install:
  # Set up the Shell to treat the semicolon as &&
  - set -eo pipefail
  # Install GHC and Cabal
  -
    cabal=${cabal=2.4};
    travis_retry sudo add-apt-repository -y ppa:hvr/ghc;
    travis_retry sudo apt-get update;
    travis_retry sudo apt-get install cabal-install-$cabal ghc-$ghc;
    export PATH=/opt/ghc/$ghc/bin:/opt/cabal/$cabal/bin:$PATH;
  # Update the Cabal database
  - cabal v1-update
  # Switch to the distro:
  - 
    export pkg_name=$(cabal info . | awk '{print $2;exit}');
    cabal sdist;
    cd dist;
    tar xzvf $pkg_name.tar.gz;
    cd $pkg_name;
  # Install the lower bound dependencies
  - 
    if [ "$lower_bound_dependencies" = "1" ];
    then
      constraint_options=(
      );
    fi;
  # Install executables
  - cabal v1-install happy
  - cabal v1-install doctest
  # Install the library dependencies
  - cabal v1-install --only-dependencies --reorder-goals --force-reinstalls
      ${constraint_options[@]}
      $([ "$tests" = "1" ] && echo "--enable-tests")
      $([ "$benchmarks" = "1" ] && echo "--enable-benchmarks")
  # Build the library
  - cabal v1-build
  # Configure and build the remaining stuff
  - cabal v1-configure 
      $([ "$tests" = "1" ] && echo "--enable-tests")
      $([ "$benchmarks" = "1" ] && echo "--enable-benchmarks")
      -f doctest
  - cabal v1-build

script:
  - |
    if [ "$tests" = "1" ];
    then
      cabal v1-doctest;
      travis_wait 40 cabal v1-test --show-details=always;
    fi;
