name: Compile, test and check the docs

on:
  workflow_call: 

jobs:

  build-with-ghc-8-10:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
    with:
      ghc: "8.10.1"
      skip-doctest: true

  build-with-latest:
    uses: nikita-volkov/haskell-hackage-lib-github-actions-workflows/.github/workflows/build.yaml@v4
    secrets: inherit
